Feat/search page
abelard-l/aviasales-demo-frontend pull request #2
Opened 2018-02-23 13:24 UTC by abelard-l

https://build-anzjzroktj.now.sh/

Карточки и Header десктоп и мобильная версии.

2018-02-24 10:19 UTC, abelard-l commented
https://build-eegvrgnpqe.now.sh/

2018-02-25 10:01 UTC, abelard-l commented
https://build-tazmxslwjo.now.sh/search

2018-02-26 13:52 UTC, evgenyrodionov commented
wtf
![image](https://user-images.githubusercontent.com/775692/36673887-6de6d1d8-1b15-11e8-9329-ba03e9ac44ed.png)
![image](https://user-images.githubusercontent.com/775692/36673892-7277345e-1b15-11e8-86f3-993b7fd6549d.png)
![image](https://user-images.githubusercontent.com/775692/36673897-779351ac-1b15-11e8-87a9-b95933265066.png)

2018-02-26 13:58 UTC, imevro requested changes
очень плохо с семантикой, мутабельностью, частыми ошибками

2018-02-26 13:58 UTC, evgenyrodionov commented on .vscode/settings.json
> +  "postcssSorting.config": {
что в проекте делают твои настройки?

2018-02-26 13:58 UTC, evgenyrodionov commented on src/Header/DatePicker.js
> +  render() {
зачем ты используешь класс?

2018-02-26 13:58 UTC, evgenyrodionov commented on src/Header/SelectPassengers.js
> +    props.borderbottom &&
тупо

2018-02-26 13:58 UTC, evgenyrodionov commented on src/Header/SelectPassengers.js
> +const StringBlock = styled.div`
стрингблок? втф?

2018-02-26 13:58 UTC, evgenyrodionov commented on src/Header/SelectPassengers.js
> +const Controll = styled.div`
почему с двумя л

2018-02-26 13:58 UTC, evgenyrodionov commented on src/Header/SelectPassengers.js
> +const MinusBtn = styled.div`
почему кнопка сделана дивом

2018-02-26 13:58 UTC, evgenyrodionov commented on src/Header/SelectPassengers.js
> +  constructor() {
читай частые ошибки

2018-02-26 13:58 UTC, evgenyrodionov commented on src/Header/SelectPassengers.js
> +      childUn2: 0
infants

2018-02-26 13:58 UTC, evgenyrodionov commented on src/Header/SelectPassengers.js
> +    if (newun2 < 0) newun2 = 0;
вся мутабельность — говно, переделывай

2018-02-26 13:58 UTC, evgenyrodionov commented on src/Header/SelectPassengers.js
> +              <AddBtn onClick={() => this.change("un2", "add")} />
minus / add? почему не minus / plus?

2018-02-26 13:58 UTC, evgenyrodionov commented on src/Header/SelectPassengers.js
> +              <Num>{this.state.childUn2}</Num>
infants?

2018-02-26 13:58 UTC, evgenyrodionov commented on src/Header/Top/index.js
> +              narrow ? "col-xs-offset-0 col-xs-12" : "col-xs-offset-1 col-xs-10"
Выглядит ужасно

2018-02-26 13:58 UTC, evgenyrodionov commented on src/Header/index.js
> +  overflow: hidden;
мусор вынеси

2018-02-26 13:58 UTC, evgenyrodionov commented on src/Header/index.js
> +      showSelPas: true
showSelPas? wtf?

2018-02-26 13:58 UTC, evgenyrodionov commented on src/Header/index.js
> +      "FromDate: " + this.state.fromDate + " ToDate:" + this.state.toDate
мусор

2018-02-26 13:58 UTC, evgenyrodionov commented on src/Main/Cards/data.js
> +    date: "24 марта"
читай частые ошибки

2018-02-26 13:58 UTC, evgenyrodionov commented on src/Main/Cards/data.js
> +    country: "Испания",
читай частые ошибки

2018-02-28 08:34 UTC, abelard-l commented
28 февраля
https://build-dqpfszmsbt.now.sh/

2018-03-01 20:44 UTC, evgenyrodionov commented
Игнор замечаний → нет проверки

2018-03-03 05:24 UTC, abelard-l commented
3 марта
https://build-desrvwwgcu.now.sh/

2018-03-04 17:30 UTC, evgenyrodionov commented
Что за дыра между поиском и списком
![image](https://user-images.githubusercontent.com/775692/36948355-db5e10ee-1fea-11e8-972c-6964707a6141.png)

2018-03-04 17:35 UTC, imevro requested changes
и переделай мусор thingsRule2 и тд, что за ад?

с мутабельностью всё плохо

2018-03-04 17:35 UTC, evgenyrodionov commented on src/Header/SelectPassengers.js
> +    let newInfants = this.state.infants;
откуда мутабельность берется? переделывай всё

2018-03-04 17:35 UTC, evgenyrodionov commented on src/Header/SelectPassengers.js
> +      case "infants":
если не знаешь джаваскрипт, читай второй урок первого этапа, там сказано про мусор в виде свитч-кейса

2018-03-04 17:35 UTC, evgenyrodionov commented on src/commonComponents.js
> +export const headerNarrowGrid = "col-xs-offset-0 col-xs-12";
это что тут делает?

2018-03-04 17:35 UTC, evgenyrodionov commented on src/commonFunctions.js
> +  price += "";
нет

2018-03-04 17:35 UTC, evgenyrodionov commented on src/res/languages/rus.loc.js
> +  "From Sochi": "Из Сочи",
используй ключи, а не строки

2018-03-05 00:32 UTC, abelard-l commented
5 марта. Поправлены баги.
https://build-odwtnlxuwx.now.sh/search

2018-03-07 17:25 UTC, imevro requested changes

2018-03-07 17:25 UTC, evgenyrodionov commented on src/Header/SelectPassengers.js
> +        where === "children"
чё за дичь тут? используй es dynamic object key и сделай `this.setState({ [key]: value })`

2018-03-07 17:25 UTC, evgenyrodionov commented on src/Header/Top/index.js
> +export const headerLongGrid =
зачем ты это вообще здесь хранишь?

2018-03-07 17:25 UTC, evgenyrodionov commented on src/Main/BestPrices/data.js
> +        name: "From_Moscow",
ключи в `snake-case`

2018-03-07 17:25 UTC, evgenyrodionov commented on src/Main/BestPrices/data.js
> +        name: "From_Moscow",
да и странно как-то сделано, зачем from указывать, если ты работаешь с массивом fromCities?

2018-03-07 17:25 UTC, evgenyrodionov commented on src/Main/SpecSugg/data.js
> +      "From_Moscow_to_the_USA_from_20680_rubles_Special_offer_from_Lufthansa"
удобно?

2018-03-07 17:25 UTC, evgenyrodionov commented on src/commonFunctions.js
> +  return price.toString().replace(/(\d{1,3}(?=(\d{3})+(?:\.\d|\b)))/g, "$1 ");
http://npmjs.com

2018-03-08 20:53 UTC, abelard-l commented
https://build-odwtnlxuwx.now.sh/

2018-03-09 10:08 UTC, imevro requested changes

2018-03-09 10:08 UTC, evgenyrodionov commented on src/Main/BestPrices/BestPrice.js
> +        <FromCity>{translate(props.bestPriceInfo.cities[4].name)}</FromCity>
а почему тут не мап?

2018-03-09 10:08 UTC, evgenyrodionov commented on src/Main/BestPrices/data.js
> +        name: "FromStPetersburg",
я же говорю, snake-case, без капиталайза

2018-03-09 17:30 UTC, abelard-l commented
https://build-gijndhsndt.now.sh/
9 марта

2018-03-10 12:30 UTC, imevro requested changes

2018-03-10 12:30 UTC, evgenyrodionov commented on src/Main/BestPrices/data.js
> +        name: "from_st_petersburg",
почему snake_case-то?

2018-07-02 08:23 UTC, closed without merging